name: Build FCOS BYOL Image

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  STREAM: stable
  IMAGE_NAME: fcos-byol.qcow2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build with packer
        run: |
          sudo apt list -a packer
          sudo apt install -y --no-install-recommends packer \
             qemu-system-x86 qemu-utils guestfs-tools genisoimage
          packer plugins install github.com/hashicorp/qemu
          PACKER_LOG=1 packer build -parallel-builds=1 deb11k6.json
          cd output; sha512sum fcos-byol.qcow2 > SHA512SUMS
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/fcos-byol.qcow21
            output/SHA512SUMS