name: Build & Release
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FCOS_STREAM: stable
    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: sudo apt update && sudo apt install -y jq xz-utils qemu-utils

    - name: Download FCOS raw
      run: |
        curl -o fcos-byol.qcow2.xz https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/42.20250705.3.0/x86_64/fedora-coreos-42.20250705.3.0-openstack.x86_64.qcow2.xz
        xz -dv fcos-byol.qcow2.xz
    - name: Generate checksum
      run: sha512sum fcos-byol.qcow2 | cut -d' ' -f1 > fcos-byol.sha512 

    - name: Upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          fcos-byol.qcow2
          fcos-byol.sha512
