name: Build & Release
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FCOS_STREAM: stable
    steps:
    - uses: actions/checkout@v3

    - name: Install tools
      run: sudo apt update && sudo apt install -y jq xz-utils qemu-utils

    - name: Download FCOS raw
      run: |
        curl -o fcos-metal.raw.xz https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/42.20250705.3.0/x86_64/fedora-coreos-42.20250705.3.0-metal.x86_64.raw.xz
        xz -d fcos-metal.raw.xz

    - name: Convert to qcow2
      run: qemu-img convert -f raw -O qcow2 fcos-metal.raw fcos-byol.qcow2

    - name: Add OVH boot script
      run: |
        cat > make_image_bootable.sh <<'EOF'
        #!/bin/bash
        mount /dev/sda1 /mnt
        grub2-install --boot-directory=/mnt/boot /dev/sda
        grub2-mkconfig -o /mnt/boot/grub2/grub.cfg
        EOF
        chmod +x make_image_bootable.sh

    - name: Generate checksum
      run: sha512sum fcos-byol.qcow2 | cut -d' ' -f1 > fcos-byol.sha512

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name:   FCOS-BYOL v${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          fcos-byol.qcow2
          make_image_bootable.sh
          fcos-byol.sha512
