name: Build FCOS BYOL Image

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  STREAM: stable
  IMAGE_NAME: fcos-byol.qcow2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Install QEMU & XZ
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y qemu-utils xz-utils

      - name: Download & decompress FCOS OpenStack image
        timeout-minutes: 10
        run: |
          set -e
          docker run --rm -v $PWD:/data quay.io/coreos/coreos-installer:release \
            download -s $STREAM -p openstack -f qcow2.xz --decompress -C /data/ || \
            { echo "Failed to download and decompress image"; exit 1; }
          COREOSIMAGE=$(find $PWD -type f -name "*.qcow2*") || \
            { echo "Image not found"; exit 1; }
          echo "Found image: $COREOSIMAGE"
          mv $COREOSIMAGE ${IMAGE_NAME}

      - name: Build with packer
        run: |
          sudo apt list -a packer
          sudo apt install -y --no-install-recommends packer \
             qemu-system-x86 qemu-utils guestfs-tools genisoimage
          packer plugins install github.com/hashicorp/qemu
          PACKER_LOG=1 packer build -parallel-builds=1 deb11k6.json
          cd output; sha512sum fcos-byol.qcow2 > SHA512SUMS
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/fcos-byol.qcow2
            output/SHA512SUMS